# path_pk per (dataset, label) = split_id — shared with 4_distance_features_battery.ipynb
# and parameterised_entropy_energy_distance_benchmark_extraction.ipynb.
# path_pk: columns to group scanpaths for expected path (subset of pk).
# Keep in sync with the distance notebook when adding new datasets/labels.

PATH_PK_PER_LABEL = {
    "3D_condition_label": ["group_category_label", "group_filenumber"],
    "3D_group_category_label": ["group_subject"],
    "AFC_group_category_label": ["group_subject"],
    "AFC_mod_label": ["group_category_label", "group_filenumber"],
    "AFC_scr_label": ["group_category_label", "group_filenumber"],
    "APPC_context_group_category_label": ["group_subject"],
    "APP_group_category_label": ["group_subject"],
    "APP_known_label": ["group_category_label", "group_filenumber"],
    "APP_meta_certainty_label": ["group_category_label", "group_filenumber"],
    "APP_mod_label": ["group_category_label", "group_filenumber"],
    "ASD_ready_data_fixations_ASD_label": ["group_observation"],
    "Age_study_group_category_label": ["group_subject"],
    "Age_study_meta_age_label": ["group_category_label", "group_filenumber"],
    "Baseline_group_category_label": ["group_subject"],
    "Bias_group_category_label": ["group_subject"],
    "Crossmodal2_group_category_label": ["group_subject"],
    "Crossmodal_condition_label": ["group_category_label", "group_filenumber"],
    "Crossmodal_group_category_label": ["group_subject"],
    "Dyslexia_1_ready_data_fixations_Dyslexia_label": ["group_stimul"],
    "Dyslexia_1_ready_data_fixations_meta_Age_label": ["group_stimul"],
    "Dyslexia_1_ready_data_fixations_meta_Sex_label": ["group_stimul"],
    "Dyslexia_2_ready_data_fixations_Dyslexia_label": ["group_stimul"],
    "Dyslexia_2_ready_data_fixations_meta_Age_label": ["group_stimul"],
    "Dyslexia_Czech_ready_data_fixations_Dyslexia_label": ["group_task"],
                "Gap_gap_label": ["group_category_label", "group_filenumber"],
    "Gap_group_category_label": ["group_subject"],
    "Head_fixed_group_category_label": ["group_subject"],
    "Head_fixed_meta_condition_label": ["group_category_label", "group_filenumber"],
    "Head_fixed_meta_guided_viewing_label": ["group_category_label", "group_filenumber"],
    "Memory_1_group_category_label": ["group_subject"],
    "Memory_1_group_iteration_label": ["group_category_label", "group_filenumber"],
    "Memory_2_condition_label": ["group_category_label", "group_filenumber"],
    "Memory_2_group_category_label": ["group_category_label", "group_filenumber"],
    "Memory_2_group_iteration_label": ["group_category_label", "group_filenumber"],
    "Paris_experiment_ready_data_fixations_TEXT_TYPE_2_label": ["group_subject"],
    "Paris_experiment_ready_data_fixations_TEXT_TYPE_label": ["group_subject"],
    "Patch_group_category_label": ["group_subject"],
    "Patch_scr_label": ["group_category_label", "group_filenumber"],
    "Surgical_skills_1_fixations_Performance_label": ["group_Task"],
    "Surgical_skills_2_fixations_Performance_label": ["group_Task"],
    "Webtask_condition_label": ["group_category_label", "group_filenumber"],
    "Webtask_familiarity_label": ["group_category_label", "group_filenumber"],
    "Webtask_group_category_label": ["group_subject"],
    "Webtask_relevance_label": ["group_category_label", "group_filenumber"],
    "Webtask_school_condition_label": ["group_category_label", "group_filenumber"],
    "Webtask_school_familiarity_label": ["group_category_label", "group_filenumber"],
    "Webtask_school_group_category_label": ["group_subject"],
    "Webtask_school_relevance_label": ["group_category_label", "group_filenumber"],
    "Webtask_school_search_result_label": ["group_category_label", "group_filenumber"],
    "Webtask_search_result_label": ["group_category_label", "group_filenumber"],
}
